### ISSUE TITLE
Events data?

### ISSUE THREAD

**Issue by danielschonfeld** [Choens/blood-sugars#1]
Hello,

I was wondering if there's any chance you guys also recorded events in nightspot, such as excursive, meals and the times the pump gave a shot in and if so if you would be able to share those?

Also, I'm a relative newbie to all of this and wondering in the CSV files, how are lines that are measured by a meter vs the CGM distinguished from one another?

Thanks much!

PS - Trying to see if i can play around with machine learning to figure out a prediction model for the glucose levels.

**Comment by Choens** [comment]
Slowest reply ever!

I apologize. I really should do a better job monitoring this.

But to answer your question, no. We definitely thought about doing that, but the time commitment to doing so was prohibitive. And, unfortunately, we are not currently collecting even the blood-sugars data because of some Android/hardware problems/upgrades.
